In [1]:
import pandas as pd
df = pd.DataFrame([
    ['green' , 'M' , 10.1 , 'class1'],
    ['red' , 'L' , 13.5 , 'class2'],
    ['blue' , 'XL' , 15.3 , 'class1']
    ])
df.columns = ['color', 'size' , 'price' , 'classlabel']
df


color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [2]:
size_mapping = { 'XL':3 , 'L':2 , 'M':1}
df['size']=df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [3]:
import numpy as np
class_mapping = {label:idx for idx , label in
    enumerate(np.unique(df[ 'classlabel' ]) )}
df['classlabel']=df['classlabel'].map(class_mapping)
df



color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   blue     3   15.3           0

In [4]:
#Qui sto facendo lo stesso del blocco sopra, ma in automatico
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y


array([0, 1, 0], dtype=int64)

In [5]:
X = df[['color', 'size' , 'price']].values
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X [:, 0])
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
c_transf = ColumnTransformer([
    ( 'onehot' , OneHotEncoder(), [0]),
    ( 'nothing' , 'passthrough' , [1, 2])
    ])
c_transf. fit_transform(X).astype(float)


array([[ 0. ,  1. ,  0. ,  1. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  3. , 15.3]])